#!/usr/bin/env python
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright: Marcel Loose, 2018

"""
This program will release messages to your mailbox that were quarantined by MIMEsweeper's 
Personal Message Manager, used by ASTRON.

Modify the lines USERNAME and PASSWORD to match with your credentials.
"""

from selenium.webdriver import Chrome
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoAlertPresentException

USERNAME='<email address>'
PASSWORD='<password>'

# Create a head-less browser
opts = Options()
opts.set_headless()
assert opts.headless  # operating in headless mode
browser = Chrome('/usr/lib/chromium-browser/chromedriver', options=opts)

# Login
browser.get('https://pmm.astron.nl/MSWPMM/Common/SignIn.aspx')
browser.find_element_by_id('tbEmailAddress').send_keys(USERNAME)
browser.find_element_by_id('tbPassword').send_keys(PASSWORD)
browser.find_element_by_id('btnSignIn').click()

# Goto 'My Messages' page, select all messages and click 'Release'
# TODO: Handle multiple pages
browser.get('https://pmm.astron.nl/MSWPMM/Common/Messages.aspx')
browser.find_element_by_class_name('tdHeader').click()
browser.find_element_by_id('btnRelease').click()

# Handle popups, which only appear if you have selected any messages to release.
try:
    # Are you sure you want to release the selected messages to your mailbox?
    browser.switch_to.alert.accept()  # Press 'OK'
    # If you choose 'OK', future messages from these senders will be delivered to your mailbox.
    browser.switch_to.alert.dismiss()  # Press 'Cancel'; we don't want to litter our Safe List.
except NoAlertPresentException:
    pass

# Sign out
browser.find_element_by_id('navigation_logoff').click()

# Close browser
browser.close()

